name: Docker Build and Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
      id: meta
      - uses: docker/metadata-action@v3
      with:
        images: rkt2u/python-helloworld
      - uses: docker/build-push-action@v2
      with:
        push: true
        tags: rkt2u/python-helloworld:latest

